function EnergyTable({ plan }) {
  if (!plan || plan.length === 0) {
    return null;
  }

  return (
    <section className="table-section">

      <div className="section-heading">

        <p className="eyebrow">
          24-HOUR PLAN
        </p>

        <h2>
          Energy Schedule
        </h2>

        <p>
          Hour-by-hour energy allocation
          generated by GridWise.
        </p>

      </div>


      <div className="table-wrapper">

        <table>

          <thead>

            <tr>

              <th>
                Hour
              </th>

              <th>
                Demand
              </th>

              <th>
                Solar
              </th>

              <th>
                Solar Used
              </th>

              <th>
                Grid
              </th>

              <th>
                Battery
              </th>

              <th>
                Cost
              </th>

              <th>
                Action
              </th>

            </tr>

          </thead>


          <tbody>

            {plan.map(
              (item, index) => (

                <tr key={index}>

                  <td>
                    {String(
                      item.hour
                    ).padStart(2, "0")}
                  </td>

                  <td>
                    {Number(
                      item.demand_kwh || 0
                    ).toFixed(2)}
                  </td>

                  <td>
                    {Number(
                      item.solar_kwh || 0
                    ).toFixed(2)}
                  </td>

                  <td>
                    {Number(
                      item.solar_used_kwh || 0
                    ).toFixed(2)}
                  </td>

                  <td>
                    {Number(
                      item.grid_kwh || 0
                    ).toFixed(2)}
                  </td>

                  <td>
                    {Number(
                      item.battery_kwh || 0
                    ).toFixed(2)}
                  </td>

                  <td>
                    ৳
                    {Number(
                      item.cost_bdt || 0
                    ).toFixed(2)}
                  </td>

                  <td>
                    {item.action}
                  </td>

                </tr>

              )
            )}

          </tbody>

        </table>

      </div>

    </section>
  );
}

export default EnergyTable;